### PR TITLE
fix edited comment event

### LINKED ISSUE #25: handle edited comment properly
currently it sends the wrong body which results in an empty body, it should send `changes.body.from` (old) and `comments.body` (new)

### PR DESCRIPTION
**Pull request by Slowlife01**
Fixes #25

### CODE REVIEW

File: src/presentation/event-handlers/Issues.ts [hunk 1]
```diff
@@ -131,14 +131,16 @@ export class IssuesEventHandler implements IIssueEvent {
 
   commentEdited(): HandlerFunction<"issue_comment.edited"> {
     return (event) => {
-      const body = markdownToHTML(event.payload.issue?.body ?? "");
+      const oldBody = markdownToHTML(event.payload.changes!.body.from ?? "");
```
Comment (elianiva) [inline src/presentation/event-handlers/Issues.ts:134]: It's safer to use `?.` instead

```suggestion
      const oldBody = markdownToHTML(event.payload.changes?.body.from ?? "");
```

**Review by elianiva — CHANGES_REQUESTED** [review]

**Review by elianiva — APPROVED** [review]
